# Generated by Django 4.0.2 on 2022-02-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='board_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board'),
        ),
    ]
