# Generated by Django 4.0.2 on 2022-02-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_task_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='access_code',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
    ]
