# Generated by Django 4.0.2 on 2022-02-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_access_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='board_id',
            new_name='board',
        ),
    ]
