# Generated by Django 4.0.2 on 2022-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_board_id_userprofile_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created_by',
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
