# Generated by Django 4.0.2 on 2022-02-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='current_wip',
            field=models.IntegerField(default=0),
        ),
    ]
