# Generated by Django 4.0.2 on 2022-03-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
