# Generated by Django 4.0.2 on 2022-03-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board'),
        ),
    ]
